# Generated by Django 5.1.4 on 2025-01-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
