# Generated by Django 5.1.4 on 2025-01-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagenes/'),
        ),
    ]
