# Generated by Django 5.1.4 on 2025-01-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duracion',
            field=models.PositiveIntegerField(default=30, help_text='Duración del servicio en minutos'),
        ),
        migrations.AlterField(
            model_name='service',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
